#include "doomdef.h"
/* generated by multigen */

const char * const sprnames[NUMSPRITES] = {
"PLAY",
"BBLS",
"BOM1",
"BOM2",
"BOM3",
"BUBL",
"BUS1",
"BUS2",
"DRWN",
"EGGM",
"FISH",
"FL01",
"FL02",
"FL03",
"FL12",
"FWR1",
"FWR2",
"FWR3",
"GFZD",
"JETF",
"MISL",
"MSTV",
"POSS",
"RING",
"ROIA",
"RSPR",
"SCOR",
"SIGN",
"SPLH",
"SPRK",
"SPRR",
"SPRY",
"STPT",
"TOKE",
"TV1U",
"TVAR",
"TVAT",
"TVEL",
"TVFO",
"TVIV",
"TVRI",
"TVSS",
"YSPR",
"GFZF",
"GFZG",
"GFZR",
};

void A_Chase(mobj_t *actor);
void A_Scream(mobj_t *actor);
void A_XScream(mobj_t *actor);
void A_Fall(mobj_t *actor);
void A_Look(mobj_t *actor);
void A_Pain(mobj_t *actor);

#define STATE(sprite,frame,tics,action,nextstate) {sprite,frame,tics,nextstate,action}

const state_t	states[NUMSTATES] = {
STATE(SPR_PLAY,0,-1,NULL,S_NULL),	// S_NULL
STATE(SPR_PLAY,0,45,NULL,S_PLAY_TAP1),	// S_PLAY_STND
STATE(SPR_PLAY,1,7,NULL,S_PLAY_TAP2), // S_PLAY_TAP1
STATE(SPR_PLAY,2,7,NULL,S_PLAY_TAP1), // S_PLAY_TAP2
STATE(SPR_PLAY,3,1,NULL,S_PLAY_RUN2),	// S_PLAY_RUN1
STATE(SPR_PLAY,4,1,NULL,S_PLAY_RUN3),	// S_PLAY_RUN2
STATE(SPR_PLAY,5,1,NULL,S_PLAY_RUN4),	// S_PLAY_RUN3
STATE(SPR_PLAY,6,1,NULL,S_PLAY_RUN5),	// S_PLAY_RUN4
STATE(SPR_PLAY,7,1,NULL,S_PLAY_RUN6),	// S_PLAY_RUN5
STATE(SPR_PLAY,8,1,NULL,S_PLAY_RUN7),	// S_PLAY_RUN6
STATE(SPR_PLAY,9,1,NULL,S_PLAY_RUN8),	// S_PLAY_RUN7
STATE(SPR_PLAY,10,1,NULL,S_PLAY_RUN1),	// S_PLAY_RUN8
STATE(SPR_PLAY,11,1,NULL,S_PLAY_SPD2), // S_PLAY_SPD1
STATE(SPR_PLAY,12,1,NULL,S_PLAY_SPD3), // S_PLAY_SPD2
STATE(SPR_PLAY,13,1,NULL,S_PLAY_SPD4), // S_PLAY_SPD3
STATE(SPR_PLAY,14,1,NULL,S_PLAY_SPD1), // S_PLAY_SPD4
STATE(SPR_PLAY,15,350,NULL,S_PLAY_FALL1),	// S_PLAY_PAIN
STATE(SPR_PLAY,16,-1,A_Fall,S_NULL),	// S_PLAY_DIE
STATE(SPR_PLAY,17,-1,A_Fall,S_NULL),	// S_PLAY_DROWN
STATE(SPR_PLAY,18,1,NULL,S_PLAY_ATK2), // S_PLAY_ATK1
STATE(SPR_PLAY,19,1,NULL,S_PLAY_ATK3), // S_PLAY_ATK2
STATE(SPR_PLAY,20,1,NULL,S_PLAY_ATK4), // S_PLAY_ATK3
STATE(SPR_PLAY,21,1,NULL,S_PLAY_ATK5), // S_PLAY_ATK4
STATE(SPR_PLAY,22,1,NULL,S_PLAY_ATK1), // S_PLAY_ATK5
STATE(SPR_PLAY,23,1,NULL,S_PLAY_DASH2), // S_PLAY_DASH1
STATE(SPR_PLAY,24,1,NULL,S_PLAY_DASH3), // S_PLAY_DASH2
STATE(SPR_PLAY,25,1,NULL,S_PLAY_DASH4), // S_PLAY_DASH3
STATE(SPR_PLAY,26,1,NULL,S_PLAY_DASH1), // S_PLAY_DASH4
STATE(SPR_PLAY,27,14,NULL,S_PLAY_RUN1), // S_PLAY_GASP
STATE(SPR_PLAY,28,-1,NULL,S_PLAY_FALL1), // S_PLAY_SPRING
STATE(SPR_PLAY,29,2,NULL,S_PLAY_FALL2), // S_PLAY_FALL1
STATE(SPR_PLAY,30,2,NULL,S_PLAY_FALL1), // S_PLAY_FALL2
STATE(SPR_PLAY,31,12,NULL,S_PLAY_TEETER2), // S_PLAY_TEETER1
STATE(SPR_PLAY,32,12,NULL,S_PLAY_TEETER1), // S_PLAY_TEETER2
STATE(SPR_PLAY,33,-1,NULL,S_NULL), // S_PLAY_HANG
STATE(SPR_POSS,0,5,A_Look,S_POSS_STND2),	/* S_POSS_STND */
STATE(SPR_POSS,1,5,A_Look,S_POSS_STND),	/* S_POSS_STND2 */
STATE(SPR_POSS,0,2,A_Chase,S_POSS_RUN2),	/* S_POSS_RUN1 */
STATE(SPR_POSS,0,2,A_Chase,S_POSS_RUN3),	/* S_POSS_RUN2 */
STATE(SPR_POSS,1,2,A_Chase,S_POSS_RUN4),	/* S_POSS_RUN3 */
STATE(SPR_POSS,1,2,A_Chase,S_POSS_RUN5),	/* S_POSS_RUN4 */
STATE(SPR_POSS,2,2,A_Chase,S_POSS_RUN6),	/* S_POSS_RUN5 */
STATE(SPR_POSS,2,2,A_Chase,S_POSS_RUN7),	/* S_POSS_RUN6 */
STATE(SPR_POSS,3,2,A_Chase,S_POSS_RUN8),	/* S_POSS_RUN7 */
STATE(SPR_POSS,3,2,A_Chase,S_POSS_RUN1),	/* S_POSS_RUN8 */
STATE(SPR_RING,0,2,NULL,S_RING2), // S_RING1
STATE(SPR_RING,1,2,NULL,S_RING3), // S_RING2
STATE(SPR_RING,2,2,NULL,S_RING4), // S_RING3
STATE(SPR_RING,3,2,NULL,S_RING5), // S_RING4
STATE(SPR_RING,4,2,NULL,S_RING6), // S_RING5
STATE(SPR_RING,5,2,NULL,S_RING7), // S_RING6
STATE(SPR_RING,6,2,NULL,S_RING8), // S_RING7
STATE(SPR_RING,5,2,NULL,S_RING9), // S_RING8
STATE(SPR_RING,4,2,NULL,S_RING10), // S_RING9
STATE(SPR_RING,3,2,NULL,S_RING11), // S_RING10
STATE(SPR_RING,2,2,NULL,S_RING12), // S_RING11
STATE(SPR_RING,1,2,NULL,S_RING1), // S_RING12
};

#undef STATE

const mobjinfo_t mobjinfo[NUMMOBJTYPES] = {

{		/* MT_PLAYER */
-1,		/* doomednum */
S_PLAY_STND,		/* spawnstate */
100,		/* spawnhealth */
S_PLAY_RUN1,		/* seestate */
sfx_None,		/* seesound */
0,		/* reactiontime */
sfx_None,		/* attacksound */
S_PLAY_PAIN,		/* painstate */
255,		/* painchance */
sfx_plpain,		/* painsound */
S_NULL,		/* meleestate */
S_PLAY_ATK1,		/* missilestate */
S_PLAY_DIE,		/* deathstate */
S_PLAY_DIE,		/* xdeathstate */
sfx_pldeth,		/* deathsound */
0,		/* speed */
16*FRACUNIT,		/* radius */
56*FRACUNIT,		/* height */
100,		/* mass */
0,		/* damage */
sfx_None,		/* activesound */
MF_SOLID|MF_SHOOTABLE		/* flags */
 },

{		/* MT_POSSESSED */
100,		/* doomednum */
S_POSS_STND,		/* spawnstate */
20,		/* spawnhealth */
S_POSS_RUN1,		/* seestate */
sfx_posit1,		/* seesound */
8,		/* reactiontime */
sfx_pistol,		/* attacksound */
S_POSS_STND,		/* painstate */
200,		/* painchance */
sfx_popain,		/* painsound */
0,		/* meleestate */
S_NULL,		/* missilestate */
S_POSS_STND,		/* deathstate */
S_POSS_STND,		/* xdeathstate */
sfx_podth1,		/* deathsound */
8,		/* speed */
20*FRACUNIT,		/* radius */
56*FRACUNIT,		/* height */
100,		/* mass */
0,		/* damage */
sfx_posact,		/* activesound */
MF_SOLID|MF_SHOOTABLE		/* flags */
 },

{           // MT_RING
	300,            // doomednum
	S_RING1,         // spawnstate
	1000,           // spawnhealth
	S_NULL,         // seestate
	sfx_None,       // seesound
	0,//MT_FLINGRING,   // reactiontime
	sfx_None,       // attacksound
	S_NULL,         // painstate
	0,              // painchance
	sfx_None,       // painsound
	S_NULL,         // meleestate
	S_NULL,         // missilestate
	S_NULL,//S_SPRK1,        // deathstate
	S_NULL,         // xdeathstate
	sfx_itemup,     // deathsound
	38,    // speed
	16*FRACUNIT,    // radius
	24*FRACUNIT,    // height
	100,            // mass
	0,              // damage
	sfx_None,       // activesound
	MF_SPECIAL|MF_NOGRAVITY, // flags
}
};

