#include "doomdef.h"
/* generated by multigen */

const char * const sprnames[NUMSPRITES] = {
"PLAY",
"BBLS",
"BOM1",
"BOM2",
"BOM3",
"BUBL",
"BUS1",
"BUS2",
"DRWN",
"EGGM",
"FISH",
"FL01",
"FL02",
"FL03",
"FL12",
"FWR1",
"FWR2",
"FWR3",
"GFZD",
"JETF",
"MISL",
"MSTV",
"POSS",
"RING",
"ROIA",
"RSPR",
"SCOR",
"SIGN",
"SPLH",
"SPRK",
"SPRR",
"SPRY",
"STPT",
"TOKE",
"TV1U",
"TVAR",
"TVAT",
"TVEL",
"TVFO",
"TVIV",
"TVRI",
"TVSS",
"YSPR",
};

void A_Chase(mobj_t *actor);
void A_Scream(mobj_t *actor);
void A_XScream(mobj_t *actor);
void A_Fall(mobj_t *actor);
void A_Look(mobj_t *actor);
void A_Pain(mobj_t *actor);

#define STATE(sprite,frame,tics,action,nextstate) {sprite,frame,tics,nextstate,action}

const state_t	states[NUMSTATES] = {
STATE(SPR_PLAY,0,-1,NULL,S_NULL),	/* S_NULL */
STATE(SPR_PLAY,0,-1,NULL,S_NULL),	/* S_PLAY */
STATE(SPR_PLAY,0,2,NULL,S_PLAY_RUN2),	/* S_PLAY_RUN1 */
STATE(SPR_PLAY,1,2,NULL,S_PLAY_RUN3),	/* S_PLAY_RUN2 */
STATE(SPR_PLAY,2,2,NULL,S_PLAY_RUN4),	/* S_PLAY_RUN3 */
STATE(SPR_PLAY,3,2,NULL,S_PLAY_RUN1),	/* S_PLAY_RUN4 */
STATE(SPR_PLAY,4,2,NULL,S_PLAY_ATK2),	/* S_PLAY_ATK1 */
STATE(SPR_PLAY,32773,4,NULL,S_PLAY),	/* S_PLAY_ATK2 */
STATE(SPR_PLAY,6,2,NULL,S_PLAY_PAIN2),	/* S_PLAY_PAIN */
STATE(SPR_PLAY,6,2,A_Pain,S_PLAY),	/* S_PLAY_PAIN2 */
STATE(SPR_PLAY,7,5,NULL,S_PLAY_DIE2),	/* S_PLAY_DIE1 */
STATE(SPR_PLAY,8,5,A_Scream,S_PLAY_DIE3),	/* S_PLAY_DIE2 */
STATE(SPR_PLAY,9,5,A_Fall,S_PLAY_DIE4),	/* S_PLAY_DIE3 */
STATE(SPR_PLAY,10,5,NULL,S_PLAY_DIE5),	/* S_PLAY_DIE4 */
STATE(SPR_PLAY,11,5,NULL,S_PLAY_DIE6),	/* S_PLAY_DIE5 */
STATE(SPR_PLAY,12,5,NULL,S_PLAY_DIE7),	/* S_PLAY_DIE6 */
STATE(SPR_PLAY,13,-1,NULL,S_NULL),	/* S_PLAY_DIE7 */
STATE(SPR_POSS,0,5,A_Look,S_POSS_STND2),	/* S_POSS_STND */
STATE(SPR_POSS,1,5,A_Look,S_POSS_STND),	/* S_POSS_STND2 */
STATE(SPR_POSS,0,2,A_Chase,S_POSS_RUN2),	/* S_POSS_RUN1 */
STATE(SPR_POSS,0,2,A_Chase,S_POSS_RUN3),	/* S_POSS_RUN2 */
STATE(SPR_POSS,1,2,A_Chase,S_POSS_RUN4),	/* S_POSS_RUN3 */
STATE(SPR_POSS,1,2,A_Chase,S_POSS_RUN5),	/* S_POSS_RUN4 */
STATE(SPR_POSS,2,2,A_Chase,S_POSS_RUN6),	/* S_POSS_RUN5 */
STATE(SPR_POSS,2,2,A_Chase,S_POSS_RUN7),	/* S_POSS_RUN6 */
STATE(SPR_POSS,3,2,A_Chase,S_POSS_RUN8),	/* S_POSS_RUN7 */
STATE(SPR_POSS,3,2,A_Chase,S_POSS_RUN1),	/* S_POSS_RUN8 */
};

#undef STATE

const mobjinfo_t mobjinfo[NUMMOBJTYPES] = {

{		/* MT_PLAYER */
-1,		/* doomednum */
S_PLAY,		/* spawnstate */
100,		/* spawnhealth */
S_PLAY_RUN1,		/* seestate */
sfx_None,		/* seesound */
0,		/* reactiontime */
sfx_None,		/* attacksound */
S_PLAY_PAIN,		/* painstate */
255,		/* painchance */
sfx_plpain,		/* painsound */
S_NULL,		/* meleestate */
S_PLAY_ATK1,		/* missilestate */
S_PLAY_DIE1,		/* deathstate */
S_PLAY_DIE1,		/* xdeathstate */
sfx_pldeth,		/* deathsound */
0,		/* speed */
16*FRACUNIT,		/* radius */
56*FRACUNIT,		/* height */
100,		/* mass */
0,		/* damage */
sfx_None,		/* activesound */
MF_SOLID|MF_SHOOTABLE|MF_DROPOFF|MF_PICKUP|MF_NOTDMATCH		/* flags */
 },

{		/* MT_POSSESSED */
3004,		/* doomednum */
S_POSS_STND,		/* spawnstate */
20,		/* spawnhealth */
S_POSS_RUN1,		/* seestate */
sfx_posit1,		/* seesound */
8,		/* reactiontime */
sfx_pistol,		/* attacksound */
S_POSS_STND,		/* painstate */
200,		/* painchance */
sfx_popain,		/* painsound */
0,		/* meleestate */
S_NULL,		/* missilestate */
S_POSS_STND,		/* deathstate */
S_POSS_STND,		/* xdeathstate */
sfx_podth1,		/* deathsound */
8,		/* speed */
20*FRACUNIT,		/* radius */
56*FRACUNIT,		/* height */
100,		/* mass */
0,		/* damage */
sfx_posact,		/* activesound */
MF_SOLID|MF_SHOOTABLE|MF_COUNTKILL		/* flags */
 },

};

