#include "doomdef.h" 
 
/* 
 *  Information about all the music 
 */ 
 
const musicinfo_t S_music[] = 
{ 
  { 0 }, 
  { "m_e1m1", 0 },
  { "m_e1m2", 0 },
  { "m_e1m4", 0 },
  { "m_e1m6", 0 },
  { "m_e2m1", 0 },
  { "m_e2m2", 0 },
  { "m_e2m3", 0 },
  { "m_e2m6", 0 },
  { "m_e2m8", 0 },
  { "m_e3m2", 0 },
  { "m_intro", 0 }
}; 
 
 
/* 
 *  Information about all the sfx 
 */ 
const char *S_sfxnames[] =
{
  0,
  "pistol",
  "shotgn",
  "sgcock",
  "plasma",
  "bfg",
  "sawup",
  "sawidl",
  "sawful",
  "sawhit",
  "rlaunc",
  "rfly",
  "rxplod",
  "firsht",
  "firbal",
  "firxpl",
  "pstart",
  "pstop",
  "doropn",
  "dorcls",
  "stnmov",
  "swtchn",
  "swtchx",
  "plpain",
  "dmpain",
  "popain",
  "slop",
  "itemup",
  "wpnup",
  "oof",
  "telept",
  "posit1",
  "posit2",
  "posit3",
  "bgsit1",
  "bgsit2",
  "sgtsit",
  "cacsit",
  "brssit",
  "cybsit",
  "spisit",
  "sklatk",
  "sgtatk",
  "claw",
  "pldeth",
  "podth1",
  "podth2",
  "podth3",
  "bgdth1",
  "bgdth2",
  "sgtdth",
  "cacdth",
  "skldth",
  "brsdth",
  "cybdth",
  "spidth",
  "posact",
  "bgact",
  "dmact",
  "noway",
  "barexp",
  "punch",
  "hoof",
  "metal",
  "itmbk",
};

#ifdef MARS
#define SOUND(sing,pri) { sing, pri, NULL }
#else
#define SOUND(sing,pri) { sing, pri, -1, -1, NULL, NULL }
#endif

sfxinfo_t S_sfx[] = 
{ 
  SOUND( 0, 0 ),
  SOUND( false, 64 ),
  SOUND( false, 64 ),
  SOUND( false, 64 ),
  SOUND( false, 64 ),
  SOUND( false, 64 ),
  SOUND( false, 64 ),
  SOUND( false, 128 ),
  SOUND( false, 64 ),
  SOUND( false, 64 ),
  SOUND( false, 64 ),
  SOUND( false, 64 ),
  SOUND( true, 70 ),
  SOUND( false, 70 ),
  SOUND( false, 70 ),
  SOUND( true, 70 ),
  SOUND( false, 100 ),
  SOUND( false, 100 ),
  SOUND( false, 100 ),
  SOUND( false, 100 ),
  SOUND( false, 100 ),
  SOUND( false, 78 ),
  SOUND( false, 78 ),
  SOUND( false, 96 ),
  SOUND( false, 96 ),
  SOUND( false, 96 ),
  SOUND( false, 78 ),
  SOUND( true, 78 ),
  SOUND( true, 78 ),
  SOUND( false, 96 ),
  SOUND( false, 32 ),
  SOUND( true, 98 ),
  SOUND( true, 98 ),
  SOUND( true, 98 ),
  SOUND( true, 98 ),
  SOUND( true, 98 ),
  SOUND( true, 98 ),
  SOUND( true, 98 ),
  SOUND( true, 94 ),
  SOUND( true, 92 ),
  SOUND( true, 90 ),
  SOUND( false, 70 ),
  SOUND( false, 70 ),
  SOUND( false, 70 ),
  SOUND( false, 32 ),
  SOUND( false, 70 ),
  SOUND( false, 70 ),
  SOUND( false, 70 ),
  SOUND( false, 70 ),
  SOUND( false, 70 ),
  SOUND( false, 70 ),
  SOUND( false, 70 ),
  SOUND( false, 70 ),
  SOUND( false, 32 ),
  SOUND( false, 32 ),
  SOUND( false, 32 ),
  SOUND( true, 120 ),
  SOUND( true, 120 ),
  SOUND( true, 120 ),
  SOUND( false, 78 ),
  SOUND( false, 60 ),
  SOUND( false, 64 ),
  SOUND( false, 120 ),
  SOUND( false, 120 ),
  SOUND( false, 120 )
}; 
 